version: '2'
services:
    scfsorgms-app:
        image: scfsorgms
        external_links:
            - scfsorgms-postgresql:postgresql
            - scfsorgms-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/scfsOrgMs
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    scfsorgms-postgresql:
        extends:
            file: postgresql.yml
            service: scfsorgms-postgresql
    scfsorgms-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: scfsorgms-elasticsearch
    consul:
        image: consul:v0.7.0 
        command: consul agent -dev -ui -client 0.0.0.0
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600

    consul-config-loader:
        image: pbesson/consul-config-loader
        volumes:
            - ./central-server-config:/config
        environment:
            - INIT_SLEEP_SECONDS=5
            - CONSUL_URL=consul
            - CONSUL_PORT=8500
        # Uncomment to load configuration into Consul from a git repository
        # as configured in central-server-config/git2consul.json
        # Also set SPRING_CLOUD_CONSUL_CONFIG_FORMAT=files on your apps
        #    - CONFIG_MODE=git
