version: '2'
services:
    scfsorgms-elasticsearch:
        container_name: scfsorgms-elasticsearch
        image: elasticsearch:2.4.0
        # volumes:
        #     - ~/volumes/jhipster/scfsOrgMs/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
